language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn install
- yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$github_token"
  local_dir: dist
  on:
    branch: master
env:
  global:
  - secure: K6yYwI1BY1C2qHmw/T3JDx6NETtYoNlQ03oQohZ7uhXHpGftIy+6a5d4YicnvRkTwE2CgYkwzUpL+uwE9/BJ9jCvSFej5iKs2TbVhITjUQ54u1cVUYddiiRiZr0W0IJHQ0jwj6//xzeQPPfDm4ee2VyxPvNZdcmuE/3vcFbEjzD27e4LFGSPx0EUb5G0/YIPMw0lJnbgLv7yTXEIsnERMhlGFnGY7V7fGb0VgMoUlZSbZgBWQvTJ/aWNSnmf9qOojApbC0glhsSwNyagmm9B3M8soa/mVc3sQ3t9VEnWSEj5XFKjQ+RdSOqaWMk4UqrFn2pjfgawpgmqVG9PifZgiZeS8LAwbez1xL9x+jYKccyR235I1F8UNLxIaFIWMhmbAJgBcZ0TOGjVSE7emyGffPnbz5vqvyQsE8KgsWjxXbvu84lz4i3OpTYTJqixNg7KJkHE3jn5NshjWG+JIsfoSzZIhMpM4gQpkaFuA9L01EamTXoXFS8rjm4dMd8No2moRaNl1UCodLkC7kJCNy1hzcuorLlqh8TEWLeiSKPNFHT1OVX1/LBi0gOkiqbpU5SJy9joGx/Q99tNj/bmqn+eQdHN2Sk+y/ltZNGmurq/jBHy9s3I1Sba50RaSLH2UlXsZmKczXFJntjLC6lMialWhrarkH0pXQ1Yf9syo+bEs60=
  - secure: GdS8TVdquX2LMJLBfb5FgeLQhPK2grIpLzxHg+wGtulIZLY+kPiB3SCUefrX8RlVc0roCysQzs+aNKIA2ACqj6F+DnBy7dm7hiSkT2QxDOtVw2w4MaV9D5SSpzM5Zd5n2QvkRpTRlLlGtdtUk7osOiOfvHKg4lrYapElGlLgQjcSS2jUF/5Pb27Yu8p+ZfwI02kRHQjFPUgWrG3tkCkq2KTrw+H6hJhMBGGBdHjw0xPSc2FBtNbvgKnXbvt6wZFrW4JPS17wSwoTbzPm/n5+f9XdahlMLiz65v1ApdO9JqvfG1OEPJMGLaLcusUZ4Mi2eVMaLYvrS3EK4NEgofEl0Uw2ZM7Jhym0zPyMPj+3/9DSda4eLMWLKsEpWPHCELO0jilpm+gdlhDSz0SYE7SmVU89dlnPgde0zDQAITXE+QlmHTReW+uBBDm8vcoAAdLE+K+7/QSelNU8mi906ODC99Ov1A9/FWIsEiXWWVFfwI6P0oMfMZSg9Nwks/kk0AUYE1c6lDabRg5OwTmbf2RpFMDg9/2w7zTWCYBjNlRgKg6DdjRv8nMPFcURyToqG1LRAETsm4NvmnMFohcLk+oeP7OBMN78rGkPwOkS6xg+fq3EttIN0+juQIjXThINnN7Z71tJRlu0tTLwP758jdytBZzrmQsw655F2S3wkEPWywc=
  - secure: D8dxW4ewc1Lbw9VJS6HdrNDJaAglu/Q7/3TP67KDx7346Z5pQ357oFWK4NURTIIyIBc9u4uz6+hOeI4eLd9CkptOmX/GugOZ9IRJZbcUajGluiC8OoCZqQ1tUs06vWPC7gKu5WTfxQ++4CvGesLSLXEjzyiuaZ8x+WrXdk9DS1c1ynWVeAFV0zl5V2xJe/M4xPIjzuLenlLrsCbK1tH4yPhjDG8dWLxbzdJKngHyI20HoSeCqxNCzIP/pdFo/EqpzRNC5AAKjhILedvE6lofuhcHo1lr13l9zLkBjogD2Phys8sPXCH7rGh8/4Vm1fq2lVbimmQ6yyn+c0S+jnQgDXOZaVehDnekMIjpT7lOnl9OGcEJo3RE64fd3Obi645boUPVU9oxwsBJ+vrt5CBnClypWCHd3DmYFzxwVIzIzmEnpBOq3oA9cx8bnOwxJ1SiC+OdPhUQH36/vPNfjAcPFnOFOd28E8CfZAVRJjKw64Jd3nl/nIDszEcHyw7aBF7qr2uMaKEG26Ag+83ZZMlBCIQHtXGgGGK71RVOd0xoMcFhU0Fo7kGLIkBJAOSZ6MGrIG5ZLzkqFihwwx3IgQ8ITzBgNl+GtfiwiqEQZvUBIg0PBuDV/pVmipif/cRijkphFdVbK5m1nPZ2ZaAslD6Fku28Zn2XT984AdeEuQYIeaA=
